version: '2.3'
services:
  mysql:
    image: mysql:5.7
    command: --init-file=/etc/mysql/race/init.sql
    networks:
      default:
        aliases:
        - mysql.race
    volumes:
    - ./configs/mysql:/etc/mysql/race
    - ./.persist/mysql:/var/lib/mysql
    environment:
      HOSTNAME: mysql.race

      MYSQL_ROOT_PASSWORD: toor

  mysql-admin:
    depends_on:
    - mysql
    image: phpmyadmin/phpmyadmin:latest
    environment:
      HOSTNAME: mysqladmin.race

      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: mysql.race
      PMA_ABSOLUTE_URI: http://mysqladmin.race

  mongo:
    image: mongo:latest
    networks:
      default:
        aliases:
        - mongo.race
    volumes:
    - ./.persist/mongo:/data/db
    environment:
      HOSTNAME: mongo.race

  mongo-admin:
    depends_on:
    - mongo
    image: mongo-express:latest
    environment:
      HOSTNAME: mongoadmin.race

      ME_CONFIG_MONGODB_SERVER: mongo.race
      ME_CONFIG_OPTIONS_EDITORTHEME: darcula
      VCAP_APP_PORT: 80

  redis:
    image: redis:latest
    networks:
      default:
        aliases:
        - redis.race
    environment:
      HOSTNAME: redis.race

  redis-admin:
    image: rediscommander/redis-commander:latest
    cap_add:
    - NET_BIND_SERVICE
    environment:
      HOSTNAME: redisadmin.race

      PORT: 80
      REDIS_HOSTS: redis.race

  nats:
    image: nats:latest
    networks:
      default:
        aliases:
        - nats.race
    environment:
      HOSTNAME: nats.race

  platform:
    scale: 2
    build:
      context: ./platform
      dockerfile: Dockerfile-dev
    image: registry.janstun.com/library/golang:develop
    working_dir: /go/src/github.com/pouyanh/anycast/platform
    volumes:
    - $GOPATH/src:/go/src

  client:
    scale: 2
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    image: registry.janstun.com/library/golang:develop
    working_dir: /go/src/github.com/pouyanh/anycast/client
    volumes:
    - $GOPATH/src:/go/src

  servant:
    scale: 2
    build:
      context: ./servant
      dockerfile: Dockerfile-dev
    image: registry.janstun.com/library/golang:develop
    working_dir: /go/src/github.com/pouyanh/anycast/servant
    volumes:
    - $GOPATH/src:/go/src
