FROM golang:latest

MAINTAINER Pouyan Heyratpour <pouyan@janstun.com>

RUN go get -v github.com/go-swagger/go-swagger/cmd/swagger
RUN go get -v github.com/codeskyblue/fswatch
ENTRYPOINT $GOPATH/bin/fswatch
